title: Project

columns:
  information:
    width: 1/2
    sections:

      meta:
        type: fields
        fields:
          roles:
            label: Your roles
            type: text
            size: large
            placeholder: E.g. Interaction Design, Visual Design
          duration:
            label: The duration
            type: text
            size: large
            placeholder: E.g. September 2019 - Januari 2019
          clients:
            label: The client(s)
            type: text
            size: large
            placeholder: E.g. NRC
          deliverables:
            label: The deliverables
            type: text
            size: large
            placeholder: E.g. Wireframes, Moodboard

  image:
    width: 1/2
    sections:

      thumbnail:
        headline: Preview image
        type: files
        template: thumbnail
        empty: Upload your preview image (File format JPEG, PNG or SVG)
        layout: cards
        multiple: false
        max: 1

  main:
    width: 1/1
    sections:

      content:
          type: fields
          fields:
            text:
              label: Editor
              type: editor