title: Site

tabs:
  dashboard:
    columns:
      - width: 1/2
        sections:
          projects: sections/projects

      - width: 1/2
        sections:
          blog: sections/articles

          pages:
            headline: Pages
            type: pages
            create: default
            templates:
              - about
              - home
              - default

  settings:
    fields:
      logo:
        label: Your logo
        empty: Upload or select a logo
        max: 1
        type: files
        layout: cards
        size: tiny
        accept: image/jpeg
      email:
        label: Your email address
        type: email
      social:
        label: Your social media links
        type: structure
        fields:
          platform:
            label: Platform name
            type: text
            width: 1/2
          url:
            label: Profile URL
            type: url
            width: 1/2